package modelo;
// Generated 05-oct-2018 10:47:59 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Articulo generated by hbm2java
 */
@Entity
@Table(name="ARTICULO"
    ,schema="CRUD_JDBC"
)
public class Articulo  implements java.io.Serializable {


     private int id;
     private String nombre;
     private double precio;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private Set<Detalle> detalles = new HashSet(0);

    public Articulo() {
    }

	
    public Articulo(int id) {
        this.id = id;
    }
    public Articulo(int id, String nombre, double precio, Date fechaCreacion, Date fechaModificacion, Set detalles) {
       this.id = id;
       this.nombre = nombre;
       this.precio = precio;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.detalles = detalles;
    }
   
    @Id 
    @Column(name="ID_ARTICULO", unique=true, nullable=false, precision=10, scale=0)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="NOMBRE", length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="PRECIO", precision=6)
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_CREACION", length=7)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_MODIFICACION", length=7)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="articulo")
    public Set<Detalle> getDetalles() {
        return this.detalles;
    }
    
    public void setDetalles(Set<Detalle> detalles) {
        this.detalles = detalles;
    }
}
