package modelo;
// Generated 05-oct-2018 10:47:59 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cabecera generated by hbm2java
 */
@Entity
@Table(name = "CABECERA",
         schema = "CRUD_JDBC"
)
public class Cabecera implements java.io.Serializable {

    
    private CabeceraId id;
    private Usuario usuario;
    private Cliente cliente;
    private Date fechaCreacion;
    private Date fechaModificacion;
    private Set<Detalle> detalles = new HashSet(0);

    public Cabecera() {
    }

    public Cabecera(CabeceraId id) {
        this.id = id;
    }

    public Cabecera(CabeceraId id, Usuario usuario, Cliente cliente, Date fechaCreacion, Date fechaModificacion, Set<Detalle> detalles) {
        this.id = id;
        this.usuario = usuario;
        this.cliente = cliente;
        this.fechaCreacion = fechaCreacion;
        this.fechaModificacion = fechaModificacion;
        this.detalles = detalles;
    }

    @EmbeddedId

    @AttributeOverrides({
        @AttributeOverride(name = "numero", column = @Column(name = "NUMERO", nullable = false, precision = 10, scale = 0))
        , 
        @AttributeOverride(name = "fecha", column = @Column(name = "FECHA", nullable = false, length = 10))})
    public CabeceraId getId() {
        return this.id;
    }

    public void setId(CabeceraId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_USUARIO")
    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_CLIENTE")
    public Cliente getCliente() {
        return this.cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "FECHA_CREACION", length = 7)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "FECHA_MODIFICACION", length = 7)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }

    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cabecera")
    public Set<Detalle> getDetalles() {
        return this.detalles;
    }

    public void setDetalles(Set<Detalle> detalles) {
        this.detalles = detalles;
    }
}
