package modelo;
// Generated 05-oct-2018 10:47:59 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CabeceraId generated by hbm2java
 */
@Embeddable
public class CabeceraId implements java.io.Serializable {

    private int numero;
    private String fecha;

    public CabeceraId() {
    }

    public CabeceraId(int numero, String fecha) {
        this.numero = numero;
        this.fecha = fecha;
    }

    @Column(name = "NUMERO", nullable = false, precision = 10, scale = 0)
    public int getNumero() {
        return this.numero;
    }

    public void setNumero(int numero) {
        this.numero = numero;
    }

    @Column(name = "FECHA", nullable = false, length = 10)
    public String getFecha() {
        return this.fecha;
    }

    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof CabeceraId)) {
            return false;
        }
        CabeceraId castOther = (CabeceraId) other;

        return (this.getNumero() == castOther.getNumero())
                && ((this.getFecha() == castOther.getFecha()) || (this.getFecha() != null && castOther.getFecha() != null && this.getFecha().equals(castOther.getFecha())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (int) this.getNumero();
        result = 37 * result + (getFecha() == null ? 0 : this.getFecha().hashCode());
        return result;
    }
}
