package modelo;
// Generated 05-oct-2018 10:47:59 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "CLIENTE",
         schema = "TPV"
)
public class Cliente implements java.io.Serializable {

    private int idCliente;
    private String nombre;
    private String cif;
    private String direccion;
    private String localidad;
    private String provincia;
    private Date fechaCreacion;
    private Date fechaModificacion;
    private Set<Cabecera> cabeceras = new HashSet(0);

    public Cliente() {
    }

    public Cliente(int idCliente) {
        this.idCliente = idCliente;
    }

    public Cliente(int idCliente, String nombre, String cif, String direccion, String localidad, String provincia, Date fechaCreacion, Date fechaModificacion, Set cabeceras) {
        this.idCliente = idCliente;
        this.nombre = nombre;
        this.cif = cif;
        this.direccion = direccion;
        this.localidad = localidad;
        this.provincia = provincia;
        this.fechaCreacion = fechaCreacion;
        this.fechaModificacion = fechaModificacion;
        this.cabeceras = cabeceras;
    }

    @Id
    @Column(name = "ID_CLIENTE", unique = true, nullable = false, precision = 10, scale = 0)
    public int getIdCliente() {
        return this.idCliente;
    }

    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }

    @Column(name = "NOMBRE", length = 30)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "CIF", length = 14)
    public String getCif() {
        return this.cif;
    }

    public void setCif(String cif) {
        this.cif = cif;
    }

    @Column(name = "DIRECCION", length = 30)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    
    @Column(name = "LOCALIDAD", length = 20)
    public String getLocalidad() {
        return this.localidad;
    }

    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }

    @Column(name = "PROVINCIA", length = 20)
    public String getProvincia() {
        return this.provincia;
    }

    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "FECHA_CREACION", length = 7)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "FECHA_MODIFICACION", length = 7)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }

    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
    public Set<Cabecera> getCabeceras() {
        return this.cabeceras;
    }

    public void setCabeceras(Set<Cabecera> cabeceras) {
        this.cabeceras = cabeceras;
    }

}
