package modelo;
// Generated 05-oct-2018 10:47:59 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DetalleId generated by hbm2java
 */
@Embeddable
public class DetalleId implements java.io.Serializable {

    private int numero;
    private String fecha;
    private int orden;

    public DetalleId() {
    }

    public DetalleId(int numero, String fecha, int orden) {
        this.numero = numero;
        this.fecha = fecha;
        this.orden = orden;
    }

    @Column(name = "NUMERO", nullable = false, precision = 10, scale = 0)
    public int getNumero() {
        return this.numero;
    }

    public void setNumero(int numero) {
        this.numero = numero;
    }

    @Column(name = "FECHA", nullable = false, length = 10)
    public String getFecha() {
        return this.fecha;
    }

    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

    @Column(name = "ORDEN", nullable = false, precision = 10, scale = 0)
    public int getOrden() {
        return this.orden;
    }

    public void setOrden(int orden) {
        this.orden = orden;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof DetalleId)) {
            return false;
        }
        DetalleId castOther = (DetalleId) other;

        return (this.getNumero() == castOther.getNumero())
                && ((this.getFecha() == castOther.getFecha()) || (this.getFecha() != null && castOther.getFecha() != null && this.getFecha().equals(castOther.getFecha())))
                && (this.getOrden() == castOther.getOrden());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (int) this.getNumero();
        result = 37 * result + (getFecha() == null ? 0 : this.getFecha().hashCode());
        result = 37 * result + (int) this.getOrden();
        return result;
    }

}
